name: amutbar_cargo
description: "AmutBar Cargo app for cargo owners and freight companies to announce loads (اعلام بار)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.11.0
  flutter_secure_storage: ^10.3.1
  connectivity_plus: ^7.3.1
  url_launcher: ^6.3.2
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1
  intl: ^0.20.3
  persian_datetime_picker: ^3.2.0
  image_picker: ^1.2.3
  permission_handler: ^13.0.0
  flutter_launcher_icons: ^0.14.4
  audioplayers: ^6.8.1
  go_router: ^17.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-FD-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_cargo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_cargo.png"
    background_color: "#fff"
    theme_color: "#00BFFE"